### ISSUE TITLE
ImportError: DLL load failed while importing QtWebEngineWidgets: Não foi possível encontrar o módulo especificado.

### ISSUE THREAD

**Issue by TarikBR** [AgnerSecurity/Agner-Browser#7]
Eu ia tentar editar esse navegador para fazer um programa do Dezeer usando o site deles, pois a versão da Microsoft Store é bugada, fica mostrando anúncios mesmo com o plano Dezeer Go, e esses anúncios não aparece pelo site, portanto queria editar isso, mas ao clicar em 'run' sem nem ter editado o código, recebo esse erro:

```
"C:\Program Files\Python39\python.exe" "C:/Users/Tarik/Downloads/Agner-Browser-main/Código em Python PT-BR/main.py"
Traceback (most recent call last):
  File "C:\Users\Tarik\Downloads\Agner-Browser-main\Código em Python PT-BR\main.py", line 4, in <module>
    from PyQt5.QtWebEngineWidgets import *
ImportError: DLL load failed while importing QtWebEngineWidgets: Não foi possível encontrar o módulo especificado.

Process finished with exit code 1
```

**Comment by AlguemVivo** [comment]
to com o mesmo erro

**Comment by TarikBR** [comment]
Eu tinha desistido, porém tentei novamente, e desinstalei a versão do Python que estava usando (3.9.7) e instalei a uma mais antiga 3.7.8 e reinstalei os módulos usando os comandos:

`pip install PyQt5`
`pip install PyQtWebEngine`

e começou a funcionar
